routes/web.php
<?php

use App\Http\Controllers\BarangController;
use App\Http\Controllers\TransaksiController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [TransaksiController::class,'index']);

Route::resource('barang',BarangController::class);
Route::resource('transaksi',TransaksiController::class);

resources/views/pages/barang-create.blade.php
@extends('layouts.layouts')

@section('content')

    <!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">List Barang</h1>
    </div>
</div>
<!-- /.container-fluid -->
<div class="container">
<form action="{{route('barang.store')}}" method="POST">
    @csrf
  <div class="form-group">
    <label for="nama_barang">Nama Barang</label>
    <input type="text" class="form-control" id="nama_barang" name="nama_barang" >
  </div>
  <div class="form-group">
    <label for="nama_barang">Harga Satuan</label>
    <input type="text" class="form-control" id="nama_barang" name="harga_satuan">
  </div>
  <div class="form-group">
    <button type="submit" class="btn btn-success">Create</button>
  </div>
</form>
</div>

@endsection

resources/views/pages/barang-edit.blade.php
@extends('layouts.layouts')

@section('content')

    <!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">List Barang</h1>
    </div>
</div>
<!-- /.container-fluid -->
<div class="container">
<form action="{{route('barang.update', $barang->id)}}" method="POST">
    @csrf
    @method('PUT')
  <div class="form-group">
    <label for="nama_barang">Nama Barang</label>
    <input type="text" class="form-control" id="nama_barang" name="nama_barang" value="{{ old('nama_barang', $barang->nama_barang) }}">
  </div>
  <div class="form-group">
    <label for="nama_barang">Harga Satuan</label>
    <input type="text" class="form-control" id="nama_barang" name="harga_satuan" value="{{ old('harga_satuan', $barang->harga_satuan) }}">
  </div>
  <div class="form-group">
    <button type="submit" class="btn btn-success">Update</button>
  </div>
</form>
</div>

@endsection

resources/views/pages/barang.blade.php
@extends('layouts.layouts')

@section('content')

    <!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">List Barang</h1>
    </div>
</div>
<!-- /.container-fluid -->
<div class="container">
    <div class="row">
        <a href="{{ url('barang/create') }}"><button class="btn btn-success">Tambah barang</button></a>
    </div>
    <br>
    <table class="table table-dark">
        <thead>
          <tr>
            <th scope="col">NO</th>
            <th scope="col">Nama Barang</th>
            <th scope="col">Harga Satuan</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
            @php
                $no=1;
            @endphp
            @foreach ($barang as $b)  
          <tr>            
            <th scope="row">{{ $no++ }}</th>
            <td>{{ $b->nama_barang }}</td>
            <td>{{ $b->harga_satuan }}</td>
            <td>
                <form 
                    action = "{{ route('barang.destroy', $b->id)}}" method="POST">
                    <a href="{{route('barang.edit', $b->id)}}" class="btn btn-warning">Edit</a>
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </td>

          </tr>
          @endforeach
        </tbody>
      </table>

</div>

@endsection

resources/views/pages/dashboard.blade.php
@extends('layouts.layouts')

@section('content')

    <!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">List Barang</h1>
    </div>
</div>
<!-- /.container-fluid -->
<div class="container">
  <form action="{{route('transaksi.store')}}" method="POST">
@csrf
      <div class="form-group">
        <label for="exampleFormControlInput1">Qty</label>
        <input type="number" id="qty">
      </div>
      <div class="form-group">
        <label for="exampleFormControlSelect1">Pilih Barang</label>       
        <select class="form-control" id="master_barang_id" name="master_barang_id" onchange="total()">
        @foreach ($barang as $b) 
        <option value={{ $b->id }}><span>{{ $b->nama_barang }}</span> harga: <span id="harga">{{$b->harga_satuan }}</span></option>
        @endforeach
        </select>        
      </div>

      <div class="form-group">
        <label for="exampleFormControlInput1">Total Harga</label>
        <input type="number" value="" id="total_harga" name="total_harga">
      </div>

      <div class="form-group">
        <button type="submit" class="btn btn-success">Beli</button>
      </div>


</form>
</div>
<script>
  function total() {
    var jumlah = document.getElementById("harga").value;
    var kuantiti = documen.getElementById("qty").value;
    var hasil = parseInt(jumlah)+parseInt(kuantiti);
    document.getElementById("total_harga").value = hasil;
}
</script>

@endsection

resources/views/pages/transaksi-create.blade.php
@extends('layouts.layouts')

@section('content')

    <!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">List Barang</h1>
    </div>
</div>
<!-- /.container-fluid -->
<div class="container">
<form action="{{route('transaksi.store')}}" method="POST">
</form>
</div>

<script>
  function data() {
      var data = document.getElementById('qty').value;
      for(data){
        document.getElementById('total_harga').value=data*'total_harga';
      }
  }
</script>

@endsection